[project]
name = "portfolio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=37.11.0",
    "fastexcel>=0.16.0",
    "polars>=1.34.0",
    "requests>=2.32.5",
    "streamlit>=1.50.0",
    "xlsxwriter>=3.2.9",
]
